### ISSUE TITLE
Todo document ?

### ISSUE THREAD

**Issue by SeleDreams** [titinko/utsu#20]
Hi, I'd still want to contribute to UTSU, but since I don't really know what is planned to be implemented, is there a kind of todo document that would tell me a bit what I should do to contribute ?

**Comment by Luk3M** [comment]
I was thinking the same... Maybe some issues could be opened with tasks contributors can do?

**Comment by titinko** [comment]
I don't have a solid TODO list up yet since I've been sick for the last few weeks, but there are some features that need to be implemented on the voicebank editor that won't conflict with the bug fixing I'm doing right now:

- Spectrogram view of sound files (can be toggled on/off)
- FRQ editor for sound files (can be toggled on/off)
- Enable zooming in sound file editor.

**Comment by timmy-larence** [comment]
Oh hi, I just learned GitHub supports Kanban boards for repos! If this idea is still relevant, wouldn't that be worth looking into? Since it allows more organized tracking of open issues and feature proposals...

**Comment by titinko** [comment]
There's a to-do list on Trello now! https://trello.com/b/8sTfttmT/utsu

**Comment by mooncat69** [comment]
Hi @titinko, I've been out of the loop for a bit. Are there any tasks you'd like me to look at?

**Comment by titinko** [comment]
@mooncat69 Thank you for offering to help!  One feature that I really need is importing other file types such as VSQ and MIDI.  I noticed on your branch that you worked with file formats a fair amount, so this might be something you're interested in?

The English locale/Japanese voicebank issue is not yet solved, especially since some resamplers don't seem to work with Unicode very well.  I'm seriously considering adding a feature that either converts voicebanks into Unicode for the user, or temporarily gives the source .wav files ASCII names before sending them to the resampler.

**Comment by mooncat69** [comment]
Thanks. I'll look into the VSQ and MIDI files.

The file format is a big one for me because it makes it very difficult for non-Japanese systems to download and use voice banks. I did do a hack that exploits the OS directory listing to get the real file name, or in the case of Windows, the safe 8.3 file name.

**Comment by SeleDreams** [comment]
I'd say it would be good to find a way to detect if a vb uses ascii or shift-jis and convert the shift-jis to unicode it would make things easier

**Comment by SeleDreams** [comment]
I am in a way thinking of creating a conversion tool of vbs to a more standard format that would allow vbs to be easier to use by UTSU, a kind of UTSU specific vb format while it would still be compatible with standard vbs

**Comment by mooncat69** [comment]
The problem there is that the unicode version of the filename doesn't match the OS version of the filename, even though it looks identical to us!
