### ISSUE TITLE
Note playback issue

### ISSUE THREAD

**Issue by LovelyA72** [titinko/utsu#21]
Expected behavior: Each note will play correctly regardless of the previous render.

Actual behavior: After doing multiple notes render and playback when the user selects one note and perform the single note playback, the user will hear the entire audio clip that previously rendered in the multiple notes render.

Version: Latest version from the master branch. Built by maven.

**Comment by mooncat69** [comment]
I've got the same on my build. I'm looking into it now.

**Comment by mooncat69** [comment]
This is an interesting one. The release 0.4 installer works correctly, but the one compiled locally, with probably exactly the same code does not work as expected. This is because the application is rendering each time to the same file called "final_song.wav" but attempts to delete it first. This deletion fails (some java process is locking the file) so the wavtool appends the new render to the end of the last render (and all renders before it).

I can fix this by creating a new temporary file for each render, but that doesn't save a cache of the last full song render and makes it more inefficient.

**Comment by LovelyA72** [comment]
Thanks for the update! I hope @titinko can come back and continue this project. It's the best open-source UTAU alternative on the whole internet!

**Comment by mooncat69** [comment]
I have a fix for this (and a few other things) in my fork at https://github.com/mooncat69/utsu . You will have to build it yourself, unfortunately, as I can't create releases.

I have made a few other fixes and optimisations. See https://github.com/mooncat69/utsu/projects/1 for some of the changes in progress.

**Comment by Kashouryo** [comment]
Thank you for keeping this project alive!

**Comment by mooncat69** [comment]
If you're comfortable running a java jar file manually (with Oracle JRE1.8), I've created a new release at https://github.com/mooncat69/utsu/releases/tag/v0.4.1-alpha.

**Comment by Kashouryo** [comment]
I got a 404 with your link. However, I also compiled a jar with maven yesterday. The issue no longer presents on your version. Thank you!

**Comment by mooncat69** [comment]
https://github.com/mooncat69/utsu/releases/tag/v0.4.1-alpha.1

**Comment by titinko** [comment]
Merged in the final_song.wav fix, I'll work on merging your fixes for resampler-output filename clashes as well.

**Comment by mooncat69** [comment]
@titinko I've lots of other changes that may interest you, generally around engine functionality, such as
* Resampler caching
* Japanese filename resolution on non Japanese Windows systems

I'm currently working on ensuring UTSU and UTAU make similar calls to the resampler and wavtool for the same UST file.

Do you have any plans / roadmaps for future development that require assistance?

**Comment by titinko** [comment]
The next step on my roadmap (https://trello.com/b/8sTfttmT/utsu) was to make User Preferences.  Right now I've just updated to a modular app with Java 14 and am working on getting deployment set up with jpackage.

My dev process right now has a big hole in it because I don't have access to a good Windows machine--I can't easily deploy on Windows or test against Windows UTAU.  Any work you do making UTSU's backend calls more similar to UTAU's would be greatly appreciated since if you can fix that, that would also fix UTSU's weird timing errors.

Also I've noticed you've added some unit tests.  I'd be happy to add those to the main branch if you make a pull request.

I'm planning on working on UTSU for the next few weeks.  Let me know if you'd like to coordinate over email or Discord!

**Comment by mooncat69** [comment]
Hi @titinko. The last thing I worked on was attempting to get UTSU to make identical calls to the resampler compared to UTAU with the same input file. I couldn't quite get this right, which I suspect makes timing drift by a few milliseconds with some notes.
