### ISSUE TITLE
VCV's struggle to render

### ISSUE THREAD

**Issue by Ivaniku** [titinko/utsu#71]
Heya, i'm using KDE Neon with the latest version of utsu and I tried utsu in my sysem, i think the video talks by itself.

Btw great job on this incredible software!

https://user-images.githubusercontent.com/56933254/106650215-efef4c80-6592-11eb-912a-15866bada1fd.mp4

**Comment by titinko** [comment]
Thanks for reporting, and including a video!

The rendering issues sound like they may be caused by the resampler.  Since you're using Linux, it's likely that you're also using the default resampler (macres) which unfortunately is often picky about which voicebanks it accepts.

So this is definitely a bug but it should be filed against macres (https://github.com/titinko/macres) rather than UTSU.  I maintain macres too though so either way I'd be the one who needs to fix it.

**Comment by Ivaniku** [comment]
> Thanks for reporting, and including a video!
> 
> The rendering issues sound like they may be caused by the resampler. Since you're using Linux, it's likely that you're also using the default resampler (macres) which unfortunately is often picky about which voicebanks it accepts.
> 
> So this is definitely a bug but it should be filed against macres (https://github.com/titinko/macres) rather than UTSU. I maintain macres too though so either way I'd be the one who needs to fix it.

Perfect! I know this is a stupid question but should i remake the issue in the macres page?

**Comment by titinko** [comment]
Yes please!
