### ISSUE TITLE
Notes are Black?

### ISSUE THREAD

**Issue by hilmiyafia** [titinko/utsu#86]
Just installed Utsu today on windows, but the notes are black, and there are no grids.

![Capture](https://user-images.githubusercontent.com/56539775/126479422-0b1d3e5c-8078-446c-a91a-a1d0cad42bd9.JPG)

**Comment by titinko** [comment]
Thanks for reporting!  A few other users have had this issue before on Windows--it happens when you CSS fails to load.  I've worked with another user to debug this issue before but haven't found anything weird about their computer, or the auto-generated CSS file.  At this point I can only think of one way to proceed, which is to find a user who:
1) Is seeing this bug on their Windows machine
2) Is tech-savvy enough to run this program from their terminal and send me whatever Java error gets printed out when the CSS fails to load.

**Comment by hilmiyafia** [comment]
@titinko You're welcome! Anyway, I think you're right. Here's what I got from running the project on Eclipse. I'm not sure why they couldn't find generated.css. I had checked the path, the file does exist.

![Capture](https://user-images.githubusercontent.com/56539775/126896149-f08e80d8-ad32-477b-87ed-e58df18662ef.JPG)

**Comment by hilmiyafia** [comment]
@

**Comment by hilmiyafia** [comment]
@titinko I'm sorry, I pressed the wrong button. But anyway, I think I have found the problem! Here's what I [found](https://stackoverflow.com/questions/33973921/javafx-font-face-css-error-loadstylesheetunprivileged/41753098):. They couldn't find the file if there are spaces in the path. Changing the cssSettingsPath solved the problem. But that's only a work around. You can't expect every computer to have a username without spaces, right?

**Comment by hilmiyafia** [comment]
@lzw-723 That seems to fix the problem! Thanks! 😀
